#!/usr/bin/env sh
iface=$(route | grep "link-local" | awk '{print $8}')
addr=$(ifconfig $iface | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')
echo "Starting Glass on $iface connecting to $addr"
adb shell am start -a android.intent.action.MAIN -n edu.oregonstate.robotics/.MainActivity -e ROS_ADDR $addr:9999